QuanLyShop/Models/KHACHHANG.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.DANHGIAs = new HashSet<DANHGIA>();
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string MaKH { get; set; }
        public string HoTen { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime NgaySinh { get; set; }
        public bool GioiTinh { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA> DANHGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
    }
}

QuanLyShop/Controllers/KHACHHANGsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuanLyShop.Models;

namespace QuanLyShop.Controllers
{
    public class KHACHHANGsController : Controller
    {
        private de_an_web_ver7Entities db = new de_an_web_ver7Entities();

        // GET: KHACHHANGs
        public ActionResult Index()
        {
            return View(db.KHACHHANGs.ToList());
        }
        public ActionResult TIMKIEMKH(string MaKH = "",  string GioiTinh = "", string ten = "", string DiaChi = "")
        {

            

                ViewBag.maHK = MaKH;
                ViewBag.gioiTinh = GioiTinh;
                ViewBag.ten = ten;

                ViewBag.diaChi = DiaChi;
               
                var khachhangs = db.KHACHHANGs.SqlQuery("KHACHHANG2_TimKiem'" + MaKH + "','" + GioiTinh + "','" + ten + "','" + DiaChi + "'");
                if (khachhangs.Count() == 0)
                    ViewBag.TB = "Không có thông tin tìm kiếm.";
                return View(khachhangs.ToList());
         }
            // GET: KHACHHANGs/Details/5
            public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KHACHHANG kHACHHANG = db.KHACHHANGs.Find(id);
            if (kHACHHANG == null)
            {
                return HttpNotFound();
            }
            return View(kHACHHANG);
        }

        // GET: KHACHHANGs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KHACHHANGs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaKH,HoTen,NgaySinh,GioiTinh,SoDienThoai,DiaChi")] KHACHHANG kHACHHANG)
        {
            if (ModelState.IsValid)
            {
                db.KHACHHANGs.Add(kHACHHANG);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kHACHHANG);
        }

        // GET: KHACHHANGs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KHACHHANG kHACHHANG = db.KHACHHANGs.Find(id);
            if (kHACHHANG == null)
            {
                return HttpNotFound();
            }
            return View(kHACHHANG);
        }

        // POST: KHACHHANGs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaKH,HoTen,NgaySinh,GioiTinh,SoDienThoai,DiaChi")] KHACHHANG kHACHHANG)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kHACHHANG).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kHACHHANG);
        }

        // GET: KHACHHANGs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KHACHHANG kHACHHANG = db.KHACHHANGs.Find(id);
            if (kHACHHANG == null)
            {
                return HttpNotFound();
            }
            return View(kHACHHANG);
        }

        // POST: KHACHHANGs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            KHACHHANG kHACHHANG = db.KHACHHANGs.Find(id);
            db.KHACHHANGs.Remove(kHACHHANG);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyShop/Controllers/QUANTRIsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using QuanLyShop.Models;

namespace QuanLyShop.Controllers
{
    public class QUANTRIsController : Controller
    {
        private de_an_web_ver7Entities db = new de_an_web_ver7Entities();

        // GET: QUANTRIs
        public bool CheckUser(string username, string password)
        {
            var kq = db.QUANTRIs.Where(x => x.Email == username && x.Password == password).ToList();
            //string hoTen = kq.First().HoTen;
            if (kq.Count() > 0)
            {
                Session["HoTen"] = kq.First().HoTen;
                return true;
            }
            else
            {
                Session["HoTen"] = null;
                return false;
            }
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(QUANTRI qt)
        {
            if (ModelState.IsValid)
            {
                if (CheckUser(qt.Email, qt.Password))
                {
                    FormsAuthentication.SetAuthCookie(qt.Email, true);
                    return RedirectToAction("Index", "QUANTRIs/Index");
                }
                else
                    ModelState.AddModelError("", "Tên đăng nhập hoặc tài khoản không đúng.");
            }
            return View(qt);
        }
        public ActionResult Index()
        {
            return View();
        }
            // GET: QUANTRIs/Details/5
            public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QUANTRI qUANTRI = db.QUANTRIs.Find(id);
            if (qUANTRI == null)
            {
                return HttpNotFound();
            }
            return View(qUANTRI);
        }

        // GET: QUANTRIs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: QUANTRIs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Email,Admin,HoTen,Password")] QUANTRI qUANTRI)
        {
            if (ModelState.IsValid)
            {
                db.QUANTRIs.Add(qUANTRI);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(qUANTRI);
        }

        // GET: QUANTRIs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QUANTRI qUANTRI = db.QUANTRIs.Find(id);
            if (qUANTRI == null)
            {
                return HttpNotFound();
            }
            return View(qUANTRI);
        }

        // POST: QUANTRIs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Email,Admin,HoTen,Password")] QUANTRI qUANTRI)
        {
            if (ModelState.IsValid)
            {
                db.Entry(qUANTRI).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(qUANTRI);
        }

        // GET: QUANTRIs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            QUANTRI qUANTRI = db.QUANTRIs.Find(id);
            if (qUANTRI == null)
            {
                return HttpNotFound();
            }
            return View(qUANTRI);
        }

        // POST: QUANTRIs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            QUANTRI qUANTRI = db.QUANTRIs.Find(id);
            db.QUANTRIs.Remove(qUANTRI);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuanLyShop/Views/KHACHHANGs/Create.cshtml
@model QuanLyShop.Models.KHACHHANG

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>KHACHHANG</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.MaKH,"Mã Khách Hàng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaKH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaKH, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HoTen,"Họ Tên", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgaySinh,"Ngày Sinh", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group1">
        @Html.LabelFor(model => model.GioiTinh, "Giới tính", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                Nam @Html.RadioButtonFor(model => model.GioiTinh, "True", new { @checked = "checked" }) &nbsp;
                Nữ @Html.RadioButtonFor(model => model.GioiTinh, "False")
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>

        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoDienThoai,"Số Điện Thoại", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DiaChi,"Địa Chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuanLyShop/Views/KHACHHANGs/Delete.cshtml
@model QuanLyShop.Models.KHACHHANG

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string gtinh = "";
}

<h4 style="color:red;"> Bạn có chắc chắn xóa thông tin này?</h4>
<table border="0" cellpadding="0" cellspacing="0" style="font-size:14px;margin-left:50px;">
    <tr>
        <td>
            <table cellpadding="2" cellspacing="10">
                <caption><b>THÔNG TIN CHI TIẾT</b></caption>
                <tr>
                   
                    <td>Mã nhân viên:</td>
                    <td>@Html.DisplayFor(model => model.MaKH)</td>
                </tr>
                <tr>
                    <td>Họ nhân viên:</td>
                    <td>@Html.DisplayFor(model => model.HoTen)</td>
                </tr>
               
                <tr>
                    <td>Ngày sinh:</td>
                    <td>@Html.DisplayFor(model => model.NgaySinh)</td>
                </tr>
                <tr>
                    <td>Giới tính:</td>
                    <td>
                        @{if (Model.GioiTinh == true)
                            { gtinh = "Nam"; }
                            else
                            { gtinh = "Nữ"; }
                        }
                        @gtinh
                    </td>
                </tr>

              
                <tr>
                    <td>SDT:</td>
                    <td>@Html.DisplayFor(model => model.SoDienThoai)</td>
                </tr>
                <tr>
                    <td>Địa chỉ:</td>
                    <td>@Html.DisplayFor(model => model.DiaChi)</td>
                </tr>
               

            </table>
        </td>
    </tr>
</table>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color" style="margin-left:50px;">
        <input type="submit" value="Xóa" class="btn btn-default" /> |
        @Html.ActionLink("Quay lại", "Index")
    </div>
}

QuanLyShop/Views/KHACHHANGs/Details.cshtml
@model QuanLyShop.Models.KHACHHANG

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string gtinh = "";
}
<h4><b>Thong tin Khách Hàng</b></h4>
    <div>
        <table border="1" cellpadding="0" cellspacing="0" style="font-size:14px;margin-left:50px;">
            <tr>
                <td>
                    <table cellpadding="2" cellspacing="10" >
                        <caption><b>THÔNG TIN CHI TIẾT</b></caption>
                        <tr>


                            <td>Mã nhân viên:</td>
                            <td>@Html.DisplayFor(model => model.MaKH)</td>
                        </tr>
                        <tr>
                            <td>Họ Tên nhân viên:</td>
                            <td>@Html.DisplayFor(model => model.HoTen)</td>
                        </tr>

                        <tr>
                            <td>Ngày sinh:</td>
                            <td>@Html.DisplayFor(model => model.NgaySinh)</td>
                        </tr>
                        <tr>

                            <td>Giới tính:</td>
                            <td>
                                @{if (Model.GioiTinh == true)
                                    { gtinh = "Nam"; }
                                    else
                                    { gtinh = "Nữ"; }
                                }
                                @gtinh
                            </td>
                        </tr>

                        <tr>
                            <td>SDT:</td>
                            <td>@Html.DisplayFor(model => model.SoDienThoai)</td>
                        </tr>
                        <tr>
                            <td>Địa chỉ:</td>
                            <td>@Html.DisplayFor(model => model.DiaChi)</td>
                        </tr>


                    </table>
                </td>
            </tr>
        </table>

    </div>
<p style="margin-left:50px;">
    @Html.ActionLink("Cập nhật", "Edit", new { id = Model.MaKH }) |
    @Html.ActionLink("Quay lại", "Index")
</p>

QuanLyShop/Views/KHACHHANGs/Edit.cshtml
@model QuanLyShop.Models.KHACHHANG

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>KHACHHANG</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaKH)
    <div class="form-group">
        @Html.LabelFor(model => model.MaKH, "Mã Khách Hàng", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaKH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HoTen, "Họ tên", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgaySinh, "Ngày sinh", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group1">
        @Html.LabelFor(model => model.GioiTinh, "Giới tính: ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">

                Nam @Html.RadioButtonFor(model => model.GioiTinh, "True", new { @checked = "checked" }) &nbsp;
                Nữ @Html.RadioButtonFor(model => model.GioiTinh, "False")
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoDienThoai, "Số Điện Thoại", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DiaChi, "Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuanLyShop/Views/KHACHHANGs/Index.cshtml
@model IEnumerable<QuanLyShop.Models.KHACHHANG>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "HoTen", rowsPerPage: 5);
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")
}

<h2><b>Danh Sách Khách Hàng</b></h2>


<button>@Html.ActionLink("Tìm Kiếm", "TIMKIEMKH")</button>

<button>@Html.ActionLink("Trở Lại", "Index", "QUANTRIs")</button>

<html>
<div id="gridContent">
    @ViewBag.TB
    @grid.GetHtml(
        tableStyle: "table table-bordered table-hover",
        footerStyle: "grid-footer",
        fillEmptyRows: true,
        mode: WebGridPagerModes.Numeric,
        alternatingRowStyle: "alternatingRowStyle",
          columns: new[]  // colums in grid
         {
            grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
            grid.Column("MaKH","Mã Khách Hàng"), //the model fields to display
            grid.Column("HoTen","Họ Tên Mã Khách Hàng"  ),

            grid.Column("NgaySinh","Ngày sinh",format:@<text> @item.NgaySinh.ToString("dd/MM/yyyy")</text>),
grid.Column("GioiTinh","Giới tính",format: (@item) => @item.GioiTinh==true?"Nam":"Nữ"),

grid.Column("SoDienThoai","Số Điện Thoại"),
grid.Column("DiaChi","Địa chỉ"),

grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "KHACHHANGs",new { id = item.MaKH },"KHACHHANGsController")),
grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","KHACHHANGs", new { id = item.MaKH },"KHACHHANGsController")),
grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","KHACHHANGs", new { id = item.MaKH },"KHACHHANGsController")),
}
)
</div>
</html>

QuanLyShop/Views/KHACHHANGs/TIMKIEMKH.cshtml
@{
    ViewBag.Title = "TIMKIEMKH";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "MaKH", rowsPerPage: 5);
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")
}

<h2>TIMKIEMKH</h2>
<html>
<head>
    <style type="text/css">
        .grid-footer {
            color: #000;
            font: 17px Calibri;
            text-align: center;
            font-weight: bold;
        }

            .grid-footer a {
                background-color: #ffffff;
                color: blue;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                padding: 1px 10px 2px 10px;
            }

                .grid-footer a:active, a:hover {
                    background-color: #ffffff;
                    color: #FFAD33;
                    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                }

        .alternatingRowStyle {
            background-color: aliceblue;
        }

        table .table1 {
            text-align: left;
            margin-left: 0px;
            margin-right: 0px;
            width: 800px;
        }

        .tr, .td {
            text-align: left;
        }
    </style>
</head>
<div>
    @using (Html.BeginForm("TIMKIEMKH", "KHACHHANGs", FormMethod.Get))
    {
        @Html.AntiForgeryToken()


    <table class="table1" align="center">
        <tr>
            <td>
                <div> Mã Khách Hàng </div>
            </td>
            <td>
                <input type="text" name="MaKH" value="@ViewBag.MaKH" />
            </td>

        </tr>
        <tr>
            <td>Giới Tính</td>
            <td>
                @if (@ViewBag.GioiTinh == null)
                {
                    <input type="radio" name="GioiTinh" value="1" /><text>Nam</text>
                    <input type="radio" name="gioiTinh" value="0" /><text>Nữ</text>
                }
                else if (@ViewBag.gioiTinh == "1")
                {
                    <input type="radio" name="GioiTinh" checked value="1" /><text>Nam</text>
                    <input type="radio" name="GioiTinh" value="0" /><text>Nữ</text>
                }
                else
                {
                    <input type="radio" name="GioiTinh" value="1" /><text>Nam</text>
                    <input type="radio" name="GioiTinh" checked value="0" /><text>Nữ</text>
                }


            </td>

        </tr>
        <tr>
            <td>Họ Tên Khách</td>
            <td>
                <input type="text" name="Hoten" value="@ViewBag.HoTen" />
            </td>
        </tr>

        <tr>
            <td>Địa Chỉ</td>
            <td>
                <input type="text" name="DiaChi" value="@ViewBag.DiaChi" />
            </td>
        </tr>

        <tr>
            <td></td>
            <td>
                <input type="submit" name="submit" value="Tìm kiếm" style="margin-left: 5px;width:100px;
                background-color: blue;color:white" />
                <input type="button" name="Nhapmoi" value="Nhập mới" style="margin-left: 5px;width:100px;
                background-color: blue;color:white" onclick="location.href='@Url.Action("TIMKIEMKH", "KHACHHANGs/TIMKIEMKH")'" />

            </td>
        </tr>
    </table>
    }
</div>

<div id="gridContent">
    @ViewBag.TB
    @grid.GetHtml(
        tableStyle: "table table-bordered table-hover",
        footerStyle: "grid-footer",
        fillEmptyRows: true,
        mode: WebGridPagerModes.Numeric,
        alternatingRowStyle: "alternatingRowStyle",
          columns: new[]  // colums in grid
         {
         
            grid.Column("MaKH","Mã Khách Hàng"), //the model fields to display
            grid.Column("HoTen","Họ Tên Mã Khách Hàng"  ),

            grid.Column("NgaySinh","Ngày sinh",format:@<text> @item.NgaySinh.ToString("dd/MM/yyyy")</text>),
grid.Column("GioiTinh","Giới tính",format: (@item) => @item.GioiTinh==true?"Nam":"Nữ"),

grid.Column("SoDienThoai","Số Điện Thoại"),
grid.Column("DiaChi","Địa chỉ"),

grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "KHACHHANGs",new { id = item.MaKH },"KHACHHANGsController")),
grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","KHACHHANGs", new { id = item.MaKH },"KHACHHANGsController")),
grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","KHACHHANGs", new { id = item.MaKH },"KHACHHANGsController")),
}
)
</div>

</html>